# Generated by Django 3.2.13 on 2022-07-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
                ('description', models.TextField()),
                ('url', models.URLField(max_length=128, unique=True)),
                ('donation_url', models.URLField(max_length=128, unique=True)),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
    ]
